### ISSUE TITLE
size=minimal: not so (on the left/right)?

### ISSUE THREAD

**Issue by dbitouze** [T-F-S/tcolorbox#105]
The following MCE shows that `size=minimal` seems to not be so (minimal), at least less on the left and on the right than on the top or the bottom:
```latex
\documentclass[12pt]{article}
\usepackage{tcolorbox}
\tcbset{%
  size=minimal,%
  colback=green%
}
\begin{document}
\sffamily\Huge%
\tcbox{lol}
\end{document}
```
![image](https://user-images.githubusercontent.com/1032633/85469582-251fcf00-b5ae-11ea-8535-beaf24ca5fac.png)

**Comment by T-F-S** [comment]
I thing, there is no problem, because `size=minimal` does what it should: setting all borders around the box to `0pt`.

The box itself comprises letters which have their own bounding box. The letter `l` needs some space left and right to be visible. This following comparison with `\fbox` should enlight the situation:

```latex
\documentclass[12pt]{article}
\usepackage{tcolorbox}
\tcbset{%
  size=minimal,%
  colback=green%
}
\begin{document}
\sffamily\Huge%
\tcbox[after=]{lol}  \fboxsep0pt\fbox{lol}
\end{document}
```

![test](https://user-images.githubusercontent.com/7982989/85516469-853e6180-b5fe-11ea-8111-8146cc658cba.jpg)

**Comment by muzimuzhi** [comment]
A bit off-topic: to visualizing boxes, luatex package `lua-visual-debug` is helpful.

```tex
\documentclass[12pt]{article}
\usepackage{tcolorbox}
\usepackage{lua-visual-debug}

\begin{document}
\sffamily\Huge
\mbox{lol}

\tcbox{lol}

\tcbox[left=5pt]{lol}

\tcbox[size=minimal]{lol}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/85545969-07ef0d00-b64f-11ea-9be9-27bb409b1836.png)
