### ISSUE TITLE
breakable boxes and \color

### ISSUE THREAD

**Issue by u-fischer** [T-F-S/tcolorbox#110]
as mentioned in the documentation colors in a breakable box are lost at the break:

~~~~
\documentclass{article}
\usepackage[most]{tcolorbox}
\usepackage{lipsum}
\begin{document}

\begin{tcolorbox}[breakable]
\lipsum[1-2]

{\color{red}\lipsum[1-3]}

\lipsum[1]
\end{tcolorbox}
\end{document}
~~~~

Imho it should be possible to avoid this at least for pdflatex and lualatex as they allow to define and use additional color stacks.

One package using a colorstack is pdfcolfoot:

~~~~
\documentclass{scrartcl}

\usepackage{pdfcolfoot,lipsum}

\begin{document}
\color{green}
\lipsum[1-3]
\footnote{\color{red}\lipsum[1-3]}
\lipsum[1]

test

\end{document}
~~~~

Another one is transparent, to store additional transparency options. 
scrlayer-notecolumn uses imho a color stack too.

**Comment by T-F-S** [comment]
I took a quick look at `pdfcolfoot` and `pdfcol`, but from it I cannot tell, if color stacks are applicable to `\vsplit` which is used for the breakable boxes. Probably, it is, because you suggested it...

With more time, I will investigate this matter further.

**Comment by u-fischer** [comment]
hm, don't trust me too much about breakable boxes, you certainly know more about it. But imho it is worth to check. How do you restore or set the colupper color in a breakable box?

**Comment by muzimuzhi** [comment]
Here is an example showing that `pdfcol` package might be applicable to `\vsplit`. The example is based on the one given in TeX-SX question [_Color bleeding when using `\vsplit` for a box with colored text_](https://tex.stackexchange.com/q/150780).

```tex
% based on https://tex.stackexchange.com/q/150780
\documentclass{article}
\usepackage{xcolor,lipsum}
\usepackage{pdfcol}

% init color stack "vsplit"
\pdfcolInitStack{vsplit}

\newbox\mwebox
\newbox\firstbox

\makeatletter
\newcommand{\savemytext}[2]{%
  \setbox\mwebox\vbox{%
    % inside \mvebox, switch to color stack "vsplit"
    \pdfcolSwitchStack{vsplit}%
    \color@begingroup\hsize=#1\relax#2\color@endgroup}}
\makeatother

\newcommand{\splitmytext}[1]{%
  \setbox\firstbox\vsplit\mwebox to #1}

\begin{document}
\savemytext{10cm}{%
  \lipsum[1]
  {\itshape\bfseries\color{red}
  \lipsum[2]
  }
  \lipsum[3]
}

\splitmytext{7cm}

% after \box\firstbox, 
% set current color to the top of default color stack
\fbox{\box\firstbox\pdfcolSetCurrent{}}

inter text

% before \box\mwebox, 
% set current color to the top of color stack "switch"
\fbox{\pdfcolSetCurrent{vsplit}\box\mwebox}

after text
\end{document}
```

![image](https://user-images.githubusercontent.com/6376638/91896375-53670c80-eccb-11ea-8608-f3e9e90b5a6d.png)

Also, as said in https://github.com/latex3/latex2e/issues/1#issuecomment-343747079, 
> (package) bigfoot implements a color stack of its own and tracks its current
state using marks ...

Hence it might be possible to has an implementation working for `dvips`-family backends, for example the `xdvipdfmx` used by xetex.

**Comment by T-F-S** [comment]
Thank you for picking up my old TeX-SX question and giving a `pdfcol` answer.

I made some additional tests with `tcolorbox` code. The color stack seems to record the color when a box is *used*, not during saving or splitting. And that is what is needed. I am not sure what happens, when a boxing-unboxing-boxing sequence is done (for some special cases), but I experienced no problems during tests.

Since `pdfcol` needs pdflatex or lualatex, distinction of cases has to be done at several (a lot of) places. Also, there are several safe-guarding code parts which may be superfluous / compatible / conflicting with the color stack code.

Currently, my conclusion is that it
- can be done
- has a high potential for (new) color bleeding side effects for existing documents

In the past, nearly every change in the color implemetation caused a lot of trouble. Nevertheless, I will continue investigations.

**Comment by u-fischer** [comment]
with lualatex the best solution is actually simply `\usepackage{luacolor}`. (We are considering to use this by default in luatex for colors). And yes, color bleeding and whatsits are quite a pain ;-). 

Side remark: in view of the work on accessibility and creating tagged pdf it would be quite useful to have hooks at the end and the begin of such splitted boxes, to close and reopen structures. The underlying problems are quite similar to the problems with to store and reinstate colors, so the work would be useful for more than "decorating" text with color.

**Comment by muzimuzhi** [comment]
Good news: Shunsaku Hirata is preparing to add support for multiple color stacks to `dvipdfm-x`, see [this message](https://tug.org/pipermail/dvipdfmx/2020-September/000105.html). This will affect both `dvipdfmx` and `xdvipdfmx`, from texlive 2021 if things go smoothly.

**Comment by T-F-S** [comment]
I just released version 4.32 with color stack support using `pdfcol`. For all my test documents, colors survive breaks now and I did not see any color bleeding.

- It should work with `pdflatex` and `lualatex`.
- It also should be compatible with `luacolor` (the old implementation was not compatible).
- With `xelatex`, it is not better or worse than before.
- I removed several **safe-guarding code parts** which were intended to plug holes years ago. I *think* they are not needed any more, but I do not remember every evil examples from the past with color bleeding ...
- I added some (not officially documented) hooks `\tcb@upperdraw@begin@hook`,
     `\tcb@upperdraw@end@hook`,  `\tcb@lowerdraw@begin@hook`, `\tcb@lowerdraw@end@hook`. They sourround upper and lower (un-)boxing. Here, the color from the private color stack is re-inserted.

**Comment by u-fischer** [comment]
Oh, nice. With xelatex/latex+dvipdfmx the situation could improve with the newest dvipdfmx version: it will have support for color stacks too.

**Comment by T-F-S** [comment]
I reopened this issue resp. feature request because of https://github.com/T-F-S/tcolorbox/issues/123

For the color stack support, a color (e.g. `tcbcolupper`) has to be saved directly or indirectly into the private color stack. This influences the vertical list in a (for me) unpredictable way. 

If no solution is found, I consider to remove the color stack support and revert back to the old algorithm.

**Comment by muzimuzhi** [comment]
> If no solution is found, I consider to remove the color stack support and revert back to the old algorithm.

Perhaps `tcolorbox` need a regression testing.

**Comment by T-F-S** [comment]
After discussion in https://tex.stackexchange.com/questions/565801/color-stack-switch-with-current-color-interferes-with-vertical-list the verdict is the following:

> version 4.42 (2020/10/09)
> - due to several problems with the color algorithm introduced with version 4.32,
>   essentially reversion to the proven pre 4.32 method.
>   * support of luacolor persists (since 4.32)
>   * color stacks (by pdfcol) are not mandatory any more,
>     but are optional now with 'use color stack'. Note that effects of whatsits
>     on the vertical space have to be expected.

The bad news is that color stacks are not the default any more.

But, the good news is that you can choose 'use color stack' optionally by cost of possible additional vertical space because of the inserted whatsit.

Also I tried to maintain luacolor compatibility (works for my test documents). For luacolor, of course, the color stack is not needed.

**Comment by u-fischer** [comment]
I think that is a good compromise.
