### ISSUE TITLE
initialization options for tcbrasters

### ISSUE THREAD

**Issue by nignasi** [T-F-S/tcolorbox#129]
This is more a question than an issue.

I think that initialization options keys cannot be applied to rasters. So what would be the recommended way to use counters or lists of rasters?

Thank you,

Ignasi

**Comment by muzimuzhi** [comment]
Could you provide more info/description? I think I didn't understand your question, especially what's the relation between initialization option keys and counters or lists of rasters.

**Comment by T-F-S** [comment]
Yes, there are no initialization options for a `tcbraster`. Since a raster is a kind of *layout helper* for arranging `tcolorbox`es, a `tcbraster` has no title, no number and therefore no special numbering support. There is a `tcboxedraster` environment, but I do not intend to make something like a `newtcboxedraster` with initialization options (seems overkill to me).

But I think, you have some application in mind where you need to number (and list) rasters. 
Well, there is no special recommended way. You could do it *anyhow* in a TeXnical way with counters. Or you could use a `tcbraster` inside a `tcolorbox` and use the initialization options of the outer `tcolorbox` (could be made invisible with the skin `empty`).

**Comment by nignasi** [comment]
Yes, you're right. My idea was to provide an answer to [this question](https://tex.stackexchange.com/q/577339/1952) in TX-SX.

Your idea about an `empty` (or `blanker`) tcolorbox around the raster in order to take profit of initialization options (counters and lists of boxes) could be valid. But in this case the "invisible" title introduces a vertical space and the `blankest` option which avoids this space won't write titles in auxiliary file for the desired listof...

In any case I agree with you that a newtcboxedrater with initialization options is not necessary. All tools provided by tcolorbox are good enough.
