### ISSUE TITLE
Differences with hbox option 

### ISSUE THREAD

**Issue by jonwrobinson** [T-F-S/tcolorbox#13]
The output from the tcolorbox environment with the 'hbox' option and the tcbox command is not the same. Is this a feature and I just missed the reason?

\documentclass[12pt]{article}
\usepackage{tcolorbox}
\begin{document}
\parindent 0pt

\begin{tcolorbox}[hbox]
  Hello world
\end{tcolorbox}

\tcbox{Hello world}

\end{document}

**Comment by T-F-S** [comment]
No, it is not a feature. I removed a lot of useless `\unskip`'s from the code, but maybe I was to eager. But I have to examine, if additional `\unskip`'s give other problems (I think, there were some).

Nevertheless, using

``` latex
\begin{tcolorbox}[hbox]
Hello world%
\end{tcolorbox}
```
will give the correct result in the meantime.

**Comment by jonwrobinson** [comment]
Thanks. That was my implicit suggestion when I first noticed the issue: http://tex.stackexchange.com/a/334270/8528

**Comment by T-F-S** [comment]
The removal of several `unskip`'s was because of some troubles with special box content as I recall now. But, I think I found a way to add them again without getting these problems.

I already implemented these changes into the brand-new version `3.95` of today. With it, the issue should b resolved (hopefully).
