### ISSUE TITLE
marvosym clashes with many packages

### ISSUE THREAD

**Issue by dbitouze** [T-F-S/tcolorbox#139]
The `marvosym` is notably known to clash with many other packages, e.g. `eurosym`. Would it be possible to replace the icon it provides used by `tcolorbox`'s `documentation` library by the ones provided by for example `fontawesome` or  `fontawesome5` (the names of commands they provide definitely don't clash with any other ones)?

**Comment by T-F-S** [comment]
I was not aware that `marvosym` is considered to be undesirable. 

Anyhow, I think only two symbols `\Righttorque` and `\Lefttorque` from `marvosym` are used for the `listings` style `tcbdocumentation`. I found no similar icons inside `fontawesome` and I fear a lot of spacing micro-changes in many documents, if I would replace these arrows.

But, instead of loading the whole `marvosym` package, I could use the `mvs` font directly, i.e. the symbols would stay as they are and no clashes with names from `marvosym` would happen.

**Comment by T-F-S** [comment]
Forgot to comment: Done with version 4.51 (2021/06/14)

**Comment by dbitouze** [comment]
> Forgot to comment: Done with version 4.51 (2021/06/14)

Works nicely, AFAICS: thanks!
