### ISSUE TITLE
Undefined control sequence. \ExplSyntaxOff

### ISSUE THREAD

**Issue by mvogt1** [T-F-S/tcolorbox#170]
Hello,

when using tcolorbox 5.0.2 I get the error:

>Undefined control sequence. \ExplSyntaxOff
>tcolorbox.sty line 2202

adding

\usepackage{xparse} to my latex document fixes this.

But shouldn't it be better that if tcolorbox depends on xparse, that it should include this
dependency by itsself?

**Comment by mvogt1** [comment]
The latest version which works for me "out of the box" is v4.30.
Starting with v4.31 I get the error.

**Comment by T-F-S** [comment]
You seem to have an old LaTeX engine.
Since at least February 2020, `expl3` is part of the LaTeX kernel, see https://www.latex-project.org/news/latex2e-news/ltnews31.pdf

Updating your LaTeX distribution will wipe away the issue. Otherwise, you have to load `expl3` or `xparse` as you already figured out.

**Comment by muzimuzhi** [comment]
`tcolorbox.sty` could use `\NeedsTeXFormat{LaTeX2e}[2020/10/01]` (for `\AddToHooks`) to declare the oldest latex2e version it depends on.

**Comment by T-F-S** [comment]
@muzimuzhi I will do that.

**Comment by T-F-S** [comment]
Done with https://github.com/T-F-S/tcolorbox/releases/tag/v5.1.0
