### ISSUE TITLE
Plain `tcolorbox` uses `autoparskip`, not `beforeafter skip balanced`

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#182]
Originally reported by @mlhetland in https://github.com/T-F-S/tcolorbox/issues/115#issuecomment-1164316963

**Example**
```tex
\documentclass[twocolumn]{article}
\usepackage{tcolorbox}
\begin{document}
\def\test{Before \begin{tcolorbox} Contents \end{tcolorbox} After}

\test
\newpage

\tcbset{beforeafter skip balanced = 0.5\baselineskip plus 2pt}
\test
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/175306865-afe48ad4-f73e-4145-a6b7-344d7a85063e.png)

**Analysis**

b9106e445ce933d24a5a880580bc8b00ede09c78 (released since v5.0.0) moved setting
```tex
\tcbset{%
  autoparskip,minipage,savedelimiter=tcolorbox,%
  set@extensions@preframe=,set@extensions@postframe=,set@extensions@final=,%
}%
```
from mid-file to the very end of `tcolorbox.sty`, even after use of `initialize@reset=reset@core`.

To demonstrate the situation after b9106e445ce933d24a5a880580bc8b00ede09c78:
```tex
% file tcolorbox.sty
\tcbset{
  initialize@reset/.code={\tcbset{#1}\appto\tcb@reset{\tcbset{#1}}},%
  reset@core/.style={
    % ...
    beforeafter skip balanced=0.5\baselineskip plus 2pt, %...
  },
  initialize@reset=reset@core,
  % ..
}

\tcbset{autoparskip, ...} % <<< this will overwrite `/tcb/before` and `/tcb/after`
```

Thus for plain `tcolorbox` on first layer, the `autoparskip` wins `beforeafter skip balanced=0.5\baselineskip plus 2pt`.

**Proposal**
Just remove that `autoparskip` used after `initialize@reset=reset@core`.

**Comment by muzimuzhi** [comment]
> [...] Now, we know why no notable changes happened...

v4.40 and v5.0.0 are released on Sep 25, 2020 and Dec 16, 2021, respectively. So 
 - the new setting had been effective for a year (and a bit longer) and for vanilla texlive 2021 (the `.iso` image), and
 - the old setting has been restored for one and a half years and for vanilla texlive 2022.

Seems only adapting the documentation gains max backward compatibility, though leaves some inconsistencies.

**Comment by T-F-S** [comment]
I just tested several of my documents with many boxes and found no critical changes, if the code is repaired.

And you bring in some new good points. I checked that your observations are correct and the new setting actually was effecive with v4.40 and gone with v5.0.0 where I moved the code with the remnant to the current position (not completely sure why) where is came to effect.

The good news (for me) is that I was not so dumb to oversee a missing new setting in v4.40... Also, all tests of this time are valid tests, because the setting *was effective*.

So, I am going to repair the code by removing the offending `autoparskip` part.

Unluckily, this came up very shortly after the release of v5.1.0. I wait until tomorrow, if new thoughts come up. Otherwise I am going to do a new release and I hope that the good people at CTAN do not curse me for updating so fast again...

**Comment by muzimuzhi** [comment]
> [...] gone with v5.0.0 where I moved the code with the remnant to the current position (not completely sure why) [...]

When tracing the problem once I moved the `\tcbset{autoparskip,minipage,...}` block back to mid-file and got a "Unknown capture mode `minipage`. [...]" error.

Hence I suspect the code movement is caused by implementing
 - #156.

The new code for `caption` style requires that the default setting `minipage`, which is a shorthand for `capture=minipage` is used after all `\tcb@@capture@<mode>` are defined.

> Otherwise I am going to do a new release and I hope that the good people at CTAN do not curse me for updating so fast again...

It's not rare that hotfix releases appear shortly after a normal release, though that's not the case for tcolorbox this time. For example during Dec 26--28, 2020, [`pgf` released](https://github.com/pgf-tikz/pgf/releases) one normal and two hotfix releases, named v3.1.8, v3.1.8a, and v3.1.8b.

**Comment by T-F-S** [comment]
Resolved with https://github.com/T-F-S/tcolorbox/releases/tag/v5.1.1
