### ISSUE TITLE
A `\sarg` for a “star argument” in ⟨parameters⟩ of `docCommand` environment?

### ISSUE THREAD

**Issue by dbitouze** [T-F-S/tcolorbox#193]
Currently, if a command, say `\mycmd`, documented with `documentation`'s `docCommand` environment has a starred variant, both `\mycmd` and `\mycmd*` have to be documented (possibly with `docCommands` environment):
```latex
\begin{docCommands}[
  doc parameter = \oarg{optional argument}\marg{mandatory argument},
]
{
  { doc name = mycmd  },
  { doc name = mycmd* },
}
\begin{itemize}
\item Bla bla for the unstarred version.
\item Bla bla for the   starred version.
\end{itemize}
\end{docCommands}
```
But most of the readers of the documentation would understand how `\mycmd` and `\mycmd*` work with a single instance `\mycmd*[⟨optional argument⟩]{⟨mandatory argument⟩}`. In particular, they would understand that the star is not part of the name and is optional, just as they would understand that `\mycmd` can be used, not only as `\mycmd[⟨optional argument⟩]{⟨mandatory argument⟩}`, but also as `\mycmd{⟨mandatory argument⟩}` (and similarly for `\mycmd*`).

Hence it would be nice to add a `\sarg` for a (very common) possible “star argument” in `⟨parameters⟩` of the `docCommand` environment. In such a case, the example above would become:
```latex
\begin{docCommand}{mycmd}{\sarg\oarg{optional argument}\marg{mandatory argument}}
\begin{itemize}
\item Bla bla for the unstarred version.
\item Bla bla for the   starred version.
\end{itemize}
\end{docCommand}
```
Note the similarity with the argument specification for `\NewDocumentCommand` and friends, which would be `s o m` for the previous example: `\NewDocumentCommand {\mycmd} {s o m} {⟨code⟩}`.

**Comment by T-F-S** [comment]
How should `\sarg` look like in the documentation? 

Using `doc name = mycmd*` would give something like

```latex
\mycomd*{some argument}
```

and `doc name = mycmd, doc parameter=\sarg...` would/should give something like

```latex
\mycomd*{some argument}
```

with `*` in other coloring?

**Comment by dbitouze** [comment]
For `doc name = mycmd, doc parameter=\sarg....`, the best for the star would be to be typeset with a different color.

Other options could be:

1. the controversial:
```latex
\mycomd(*){some argument}
```
1. if you consider the starred and the unstarred have to be distinguished, a behavior equivalent to the current:
```latex
\begin{docCommands}[
  doc parameter = \oarg{optional argument}\marg{mandatory argument},
]
{
  { doc name = mycmd  },
  { doc name = mycmd* },
}
\begin{itemize}
\item Bla bla for the unstarred version.
\item Bla bla for the   starred version.
\end{itemize}
\end{docCommands}
```

**Comment by muzimuzhi** [comment]
Another possible gain from `\sarg`: add no index entry for starred commands automatically. Currently one need to explicitly write `doc no index`:
```tex
\begin{docCommands}[
  doc parameter = \oarg{optional argument}\marg{mandatory argument},
]
{
  { doc name = mycmd  },
  { doc name = mycmd*, doc no index },
}
  ...
\end{docCommands}
```
otherwise one gets
![image](https://user-images.githubusercontent.com/6376638/218932309-c59e2e16-359d-4576-a3bb-bf0bc1cb36d0.png)


As far as the `*` is optional (the suggested use case for `\sarg`), its output can share the same color with `\oarg`.  Hence the definition for `\sarg` can be as simple as `\def\sarg{\colOpt{\ttfamily*}}`.  Mandatory `*` can be typed in directly and share the color with either `\marg` or `/tcb/doc command`.  See examples from `texdoc tikz` (`pgfmanual.pdf`) and `texdoc beamer` (`beameruserguide.pdf`):
- Optional `*`
   ![image](https://user-images.githubusercontent.com/6376638/218932648-ad25817a-a0d0-4347-a8a4-9a60018b84ca.png)
- Mandatory `*`
   ![image](https://user-images.githubusercontent.com/6376638/218932734-fccfdf0c-d4d2-4b73-88a2-5429f0f29374.png)
- Optional `*`s
   ![image](https://user-images.githubusercontent.com/6376638/218932859-426fb9d7-826a-49cc-8178-7f2a362ea4a6.png)

**Comment by T-F-S** [comment]
> Note the similarity with the argument specification for `\NewDocumentCommand` and friends, which would be `s o m` for the previous example: `\NewDocumentCommand {\mycmd} {s o m} {⟨code⟩}`.

I will add a `\sarg` macro with similar meaning as for `\NewDocumentCommand`: It is always optional (color) and it works like in `expl3` syntax. Note that for `\NewDocumentEnvironment` you still would have to create `foo` and `foo*` separately similar to `expl3`, see https://tex.stackexchange.com/questions/593923/star-argument-in-newdocumentenvironment-with-variable-name

**Comment by T-F-S** [comment]
Added with https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.2
