### ISSUE TITLE
loop for rasters or magazine fragments

### ISSUE THREAD

**Issue by nignasi** [T-F-S/tcolorbox#20]
This is an improvement suggestion, not a problem or bug.

tcolorbox offers \tcbincludepdf or a combination of \tcbincludegraphics with `graphics pages` to automatically include several pages inside a raster. But it doesn't exist this option for other possible uses like selecting enumerated external files or `magazine`-array elements. 

Even for simple tests could be easier to write:

\begin{tcbitemize}[....]
\foreach \i in {1,...,30} \tcbitem [...\i]
\end{tcbitemize}

than repeating \tcbitem thirty times.

Another application could be to provide breakable multicolumn boxes like in http://tex.stackexchange.com/a/355499/1952.

As I told you, it's just a suggestion from someone who doen't know how difficult could be its implementation.

**Comment by T-F-S** [comment]
Thank you for the suggestion. I will think about it.

**Comment by nignasi** [comment]
I've seen that recent 4.03 version says: 
- Implementation of 'raster equal height' changed to be more robust e.g. for loops

Is it related with this suggestion? If the answer is yes, could you show me an example? 

Thank you.

**Comment by T-F-S** [comment]
Yes, this was done following your suggestion.

For `tcbitemize`, I fear that there is no simple way to support loops, because of the very special way how the implementation is done. But 'normal' `tcbraster` environments can contain loops. 

Before version 4.03, loops with `\foreach` and `raster equal height=rows` would'nt work, but with 4.03 they do.

Example:

```latex
\documentclass[a4paper,12pt]{book}

\usepackage{geometry}

\usepackage[breakable,skins,raster,fitting]{tcolorbox}

\usepackage{lipsum}
\usepackage{lmodern}

\begin{document}

\definecolorseries{sheep}{rgb}{step}[rgb]{.95,.85,.55}{.17,.47,.37}
\resetcolorseries{sheep}

\begin{tcbraster}[raster equal height=rows]
\foreach \i in {1,2,...,30}
{%
  \begin{tcolorbox}[enhanced,size=small,
    title=Test \thetcbrasternum,
    colframe=sheep!50!black,colback=sheep!!+!25!white,
    fontupper=\tiny,
    ]
    \lipsum[\i]
  \end{tcolorbox}
}%
\end{tcbraster}

\end{document}
```

![test_270_output](https://cloud.githubusercontent.com/assets/7982989/25482661/09ab05ca-2b53-11e7-940f-401ef7fc2964.png)

So, loops with `tcbitemize` will not work and currently I do not see a change in future.

**But**, loops with `tcbraster` should work better now. Overall, inside a loop, a single shortcut `\tcbitem` for a `tcolorbox` is not so much a deal as having it many times. So, I think, it is not so bad to use `tcbraster` directly.
