### ISSUE TITLE
`savelowerto` works nicely in `\NewTColorBox` but not in `\DeclareTotalTColorBox`

### ISSUE THREAD

**Issue by dbitouze** [T-F-S/tcolorbox#205]
In the following MCE are defined in very similar ways:

- a `\NewTColorBox`: `EnvExercise`,
- a `\DeclareTotalTColorBox`: `\CmdExercise`,

Everything works nicely except if `savelowerto=CmdExercise-\thetcbcounter.tex` is uncommented in the `⟨options⟩` of `\DeclareTotalTColorBox`:

> ! You can't use `\unskip' in vertical mode.
> \endtcb@savebox ->\par \unskip 
>                                \ifvoid \@mpfootins \else \vskip \skip \@mpfo...
> 
> l.1921       doc@marginnote,#1]#2\end{tcolorbox}}}
>                                                 
> ?

Is there any reason for `savelowerto` to work nicely in `\NewTColorBox` but not in `\DeclareTotalTColorBox`? I didn't find anything about this in the documentation. Maybe #77 is related but I'm not sure.

```latex
\NewTColorBox[auto counter]{EnvExercise}{}{%
  lowerbox=ignored,
  savelowerto=EnvExercise-\thetcbcounter.tex,
  record={\string\solution{\thetcbcounter}{EnvExercise-\thetcbcounter.tex}},
}

\DeclareTotalTColorBox[auto counter]{\CmdExercise}{ +m +m }{
  lowerbox=ignored,
  % savelowerto=CmdExercise-\thetcbcounter.tex,
  record={\string\solution{\thetcbcounter}{CmdExercise-\thetcbcounter.tex}}
}{
  #1\tcblower#2%
}

\begin{document}
\tcbstartrecording\relax

\begin{EnvExercise}
  Foo.
  \tcblower
  Bar.
\end{EnvExercise}

\CmdExercise{Foo.}{Bar.}

\tcbstoprecording
\end{document}
```

**Comment by T-F-S** [comment]
> Is there any reason for `savelowerto` to work nicely in `\NewTColorBox` but not in `\DeclareTotalTColorBox`? I didn't find anything about this in the documentation. Maybe #77 is related but I'm not sure.

Yes, there is a relation. `savelowerto` triggers a verbatim saving starting with `\tcblower`. Saving stops when `\end{...}` of the environment is discovered. In case of `\CmdExercise` there is no end of an environment.  This is also the (or one) reason why there is no `saveupperto`, because `\tcblower` could not end the verbatim saving of the upper part.

For your example, there would be other ways to save the content of the second parameter of `\CmdExercise`, but not by `\tcblower`.

I think I should add a hint in the documentation that `savelowerto` cannot be used with `\DeclareTotalTColorBox`.

**Comment by T-F-S** [comment]
Documented with https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.0

**Comment by dbitouze** [comment]
OK, thanks. 

I'm still interested by the other ways to save the content of the second parameter of `\CmdExercise`. Indeed, for my real use case, I'd like in fact the second argument of this command to be an optional one for the solution that I can provide or not provide depending on the case and this, without relying on `\tcblower`, just like this:
```latex
\CmdExercise{Exercise statement (only)}
\CmdExercise{Exercise statement}[Exercise solution]
```

**Comment by muzimuzhi** [comment]
@dbitouze This is (again) a tokenization problem.

`savelowerto=<filename>` makes `\tcblower` call `\tcbverbatimwrite` at last, which changes current category code table (as `l3cctab` calls it) to a table for reading content line by line verbatim. This verbatim reading can only be ended if a TeX string[^1] `\end{<value passed to savedelimiter>}` is found.

But after defined as a total box, in your example `\CmdExercise` already contains tokenized `\begin{tcolorbox}[...] ... \end{tcolorbox}` (see definition of [`\__tcobox_new_TotalTColorBox:Nnnnnn`](https://github.com/T-F-S/tcolorbox/blob/92fd4672950e19e610cb8b77b25b975a485c157b/tex/latex/tcolorbox/tcolorbox.sty#L2256-L2260)) in which the part `\end{tcolorbox}` is made up of a control sequence `\end`, a begin group `{`, nine letters `tcolorbox`, and a end group `}`.  Therefore the `\tcbverbatimwrite` will never find its ending mark and will finally raise errors in some too-late stage.

Below are two retokenization-experiments using `\scantokens`:
- The first one `\myCmdExercise` wraps `EnvExercise` environment and retokenizes `\tcblower ... \end{EnvExercise}` part.
- The second one `\CmdExercise` is defined by a new factory command `\NewTotalTColorBoxRescanned`. It is similar to `\NewTotalTColorBox` but by retokenizing the whole `\begin{tcolorbox}[...] ... \end{tcolorbox}` part, it also supports `savelower`.
  - I don't think this worth to be added to `tcolorbox`, because retokenization brings new restrictions.  But in some extent I start to think maybe `tcolorbox` could expose the `<init options>` processor (currently related to `\__tcobox_process_newtcolorbox:nn {<init options>} {<box name>}` and `options@for=<box name>`).

<details><summary>Full example + output</summary>

```tex
\documentclass{article}
\usepackage{tcolorbox}

\ExplSyntaxOn
\cs_new:Npn \__tcobox_new_TotalTColorBox_rescanned:Nnnnnn #1#2#3#4#5#6
  {
    \__tcobox_process_newtcolorbox:nn { #2 }{ #3 }
    \exp_args:Nc #1 { #3 }{ #4 }
      {
        % savedelimiter=tcolorbox is essential because
        %   \__tcobox_process_newtcolorbox:nn {<init options>} {<box name>}
        % unconditionally sets `savedelimiter=<box name>`
        \begin{tcolorbox}[#5,options@for=#3,savedelimiter=tcolorbox]
        % unlike \tl_rescan:nn, \scantokens (re)tokenize one token at a time,
        % which is the feature needed here
        \exp_args:Ne \scantokens
          {
            \exp_not:n {#6 \end{tcolorbox} }
          }
      }
  }

\NewDocumentCommand \__tcobox_new_TotalTColorBox_rescanned:w { m +O{} m }
  {
    \__tcobox_set_backslash_removed:Nn \l_tmpa_tl { #3 }
    \exp_args:NNnV \__tcobox_new_TotalTColorBox_rescanned:Nnnnnn #1 {#2} \l_tmpa_tl
  }

\NewDocumentCommand \NewTotalTColorBoxRescanned { }
  {
    \bool_set_true:N \l__tcobox_prevent_init_overwrite_bool
    \__tcobox_new_TotalTColorBox_rescanned:w \NewDocumentCommand
  }
\ExplSyntaxOff


\NewTColorBox[auto counter]{EnvExercise}{}{%
  lowerbox=ignored,
  savelowerto=EnvExercise-\thetcbcounter.tex,
  record={\string\solution{\thetcbcounter}{EnvExercise-\thetcbcounter.tex}},
}

% use `+v` instead of `+m` to support catcode-changing things like \verb
\NewDocumentCommand{\myCmdExercise}{ +m +v }{%
  \begin{EnvExercise}%
    #1%
    \scantokens\expandafter{\unexpanded{\tcblower
    #2%
  \end{EnvExercise}}}%
  % we need the final newline char hence no need for a trailing \noexpand
}

\NewTotalTColorBoxRescanned[auto counter]{\CmdExercise}{ +m +m }{
  lowerbox=ignored,
  savelowerto=CmdExercise-\thetcbcounter.tex,
  record={\string\solution{\thetcbcounter}{CmdExercise-\thetcbcounter.tex}}
}{
  #1
  \tcblower
  #2
}

\providecommand{\solution}[2]{#1, 
  \InputIfFileExists{#2}{}{file \texttt{#2} not found}\par}

\begin{document}
\tcbstartrecording\relax

\begin{EnvExercise}
  EnvExercise, upper part
  \tcblower
  EnvExercise, lower part
\end{EnvExercise}

\myCmdExercise{myCmdExercise, arg 1}{myCmdExercise, arg 2
  \verb|code|
}

\CmdExercise{rescanned myCmdExercise, arg 1}{rescanned myCmdExercise, arg 2}

\tcbstoprecording

\tcbinputrecords
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/218380975-93bff66e-bc78-4e0e-a225-53245cd31f99.png)

</details>

[^1]: A TeX string is a list of tokens in which all characters are by themselves a token (think of `\def`, is it a single token or four tokens?) and have catcode 12 ("other") except that space char has catcode 10 ("space").

**Comment by dbitouze** [comment]
Very nice (and somehow beyond my scope) indeed: many thanks!

**Aside note.** I want the solution to be given in a optional argument and I don't need it to be read verbatim; but your code made me realize that, in the `usrguide,` an argument read verbatim cannot be optional.
