### ISSUE TITLE
Problem with \NewTCBInputListing and -NoValue-key for /tbc/new

### ISSUE THREAD

**Issue by cpierquet** [T-F-S/tcolorbox#212]
Hi -
Since 6.0 version, I've got a problem with `\NewTCBInputListing` and an error with `! Package pgfkeys Error: I do not know the key '/tcb/new/-NoValue-'`.

With `\NewTCBInputListing{\CodePythonLstFichier}{ O{\linewidth} m m }{...}` it's not working.
With `\NewTCBInputListing[]{\CodePythonLstFichier}{ O{\linewidth} m m }{...}` it's working.

![image](https://user-images.githubusercontent.com/45103962/218260374-c249175e-33ff-486a-b429-da2451142492.png)

![image](https://user-images.githubusercontent.com/45103962/218260416-d763283a-4025-4b8f-9017-17bb4d5a5ce9.png)

**Comment by muzimuzhi** [comment]
In v6.0.0, the check `\tl_if_novalue:nF { #1 } { \tcb@proc@options@init{#1}{#2} }` is [removed from `\__tcobox_process_newtcolorbox:nn`](https://github.com/T-F-S/tcolorbox/commit/67cf2b4ca623f2d425b2930b92f67b7b8428c73c#diff-44d905050db2fcf15c6adeec1023018aff520f938884a90e6e5e1128a826ed5bL2194). This requires any proprocessor uses `+O{}` xparse arg-spec instead of the old `+o`, which (the latter) will leave `-NoValue-` if the corresponding opt-arg is missing. Unfortunately in some places this change didn't happen.

For your case, below will help. I'll check if there's more such cases.
```tex
\documentclass{article}
\usepackage[listings]{tcolorbox}

\ExplSyntaxOn
\makeatletter
\def\tcb@temp{6.0.0}
\ifx\tcb@temp\tcb@version
  \RenewDocumentCommand \__tcobox_new_TCBInputListing:w { m +O{} m }
    {
      \__tcobox_set_backslash_removed:Nn \l_tmpa_tl { #3 }
      \exp_args:NNnV \__tcobox_new_TCBInputListing:Nnnnn #1 {#2} \l_tmpa_tl
    }
\fi
\makeatother
\ExplSyntaxOff

\begin{document}
content
\end{document}
```

**Comment by T-F-S** [comment]
Sorry for that. To correct https://github.com/T-F-S/tcolorbox/issues/194 many `+o` had to be replace by `+O{}` and I missed that one. Will be corrected soon.

**Comment by T-F-S** [comment]
Fixed with https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.1
