### ISSUE TITLE
breakable tcolorbox emits warning of "Package tcolorbox Warning: Discard zero height first box part ..."

### ISSUE THREAD

**Issue by akiyks** [T-F-S/tcolorbox#218]
Hello Thomas,

I'm observing warning messages from tcolorbox new to v6.0.0, which read:

```
Package tcolorbox Warning: Discard zero height first box part due to break problems (possible loss of zero height content) on input line nn.
```

pdflatex further complains:

```
pdfTeX warning: pdflatex: pop empty color page stack 0
```

MWE is taken from the answer to https://tex.stackexchange.com/questions/567017/some-links-disappear-with-tcolorboxenvironment-for-theorem-like-environments, with the first example excluded.

```
\documentclass{article}

\usepackage{tcolorbox}
\tcbuselibrary{breakable}

\begin{document}

\begin{tcolorbox}[breakable,label=lab2]
\rule{2cm}{19cm}
\end{tcolorbox}
No problem: lab2 \pageref{lab2} foo

\clearpage

\begin{tcolorbox}[breakable]
\mbox{}\label{lab3}
\rule{2cm}{19cm}
\end{tcolorbox}
No problem: lab3 \pageref{lab3} foo

\clearpage

\begin{tcolorbox}[breakable=false]
\label{lab4}
\rule{2cm}{19cm}
\end{tcolorbox}
No problem: lab4 \pageref{lab4} foo

\end{document}
```

Bisection points to commit dabf431037a3 ("5.1.2 (Preview 1) Color setting changed according to issue #204") as the first bad commit.
Besides the false(?) warning messages, resulting PDF looks good to me.
Still, it would be much preferable if those scary-looking warning messages can be avoided.

Can you please look into this?

Thanks, Akira

**Comment by T-F-S** [comment]
The messages are true warnings, because the color setting gets lost due to the overful boxes.

Version 6.0.0 is a major update to solve https://github.com/T-F-S/tcolorbox/issues/204. Now, colors are set at begin of the box content. These colors get lost by trying to break your example boxes which are not breakable. Therefore, the warning is correct and corresponds to the `pop empty color page stack` warning.

Using `lualatex` with `\usepackage{luacolor}` avoids these problems, but your box content has still too much height and warnings `The upper box part has become overfull on input line` will remain. Also with `tcolorbox` version 5.1.1 you have/had these overfull warnings.

**Comment by akiyks** [comment]
Thank you for the quick response!

> The messages are true warnings, because the color setting gets lost due to the overful boxes.
> 
> Version 6.0.0 is a major update to solve #204. Now, colors are set at begin of the box content. These colors get lost by trying to break your example boxes which are not breakable. Therefore, the warning is correct and corresponds to the `pop empty color page stack` warning.

Can you elaborate on what condition a breakable box is not actually breakable?

> 
> Using `lualatex` with `\usepackage{luacolor}` avoids these problems, but your box content has still too much height and warnings `The upper box part has become overfull on input line` will remain. Also with `tcolorbox` version 5.1.1 you have/had these overfull warnings.

In the real .log file I've got, there is no overfull warnings, but underfull warnings.
Excerpt from a log of pdflatex run follows (with auto wrapping undone):

```
[189]) (./defer/updates.tex) (./qqzdefer.tex [190] [191]

Package tcolorbox Warning: Discard zero height first box part due to break problems (possible loss of zero height content) on input line 185.

[192

pdfTeX warning: pdflatex: pop empty color page stack 0
] [193])) (./datastruct/datastruct.tex [194]
Chapter 10.

Underfull \vbox (badness 3386) has occurred while \output is active []

 [195

]
```

So it looks like the MWE I used above does not represent what I am observing.
I'll try to prepare a more realistic MWE, but I'm not sure how long it takes.
Our project generates several PDFs with different geometry settings from a single set of LaTeX soruces, and  uses the `nowidow` package, it is practically impossible to resolve all the underfills.

As TeX Live 2023 pretest will start shortly, I'd like to make a suggestion .

I remember you added the `\tcbsetforeverylayer{autoparskip}` knob in tcolorbox v4.40 for backward compatibility.
Actually, our project still relies on it.

I might be asking too much, but wouldn't it be possible to add a similar knob for those expecting the old behavior of breakable boxes?

**Comment by T-F-S** [comment]
> Can you elaborate on what condition a breakable box is not actually breakable?

`tcolorbox` calculates, if there is enough space on the current page (some lines). In this case, the upper box part is split into two parts. This fails, if the content starts with large unbreakable stuff like the `\rule` in your example. The box content is reassembled to start over on the next page, but things like labels or color setting can get lost (here comes the warning).

> So it looks like the MWE I used above does not represent what I am observing. I'll try to prepare a more realistic MWE, but I'm not sure how long it takes. Our project generates several PDFs with different geometry settings from a single set of LaTeX soruces, and uses the `nowidow` package, it is practically impossible to resolve all the underfills.

Apart from the warnings: Do you get (new) problems with the real world examples? I would hope that there are no fundamental changes...
 
> As TeX Live 2023 pretest will start shortly, I'd like to make a suggestion .
> 
> I remember you added the `\tcbsetforeverylayer{autoparskip}` knob in tcolorbox v4.40 for backward compatibility. Actually, our project still relies on it.
> 
> I might be asking too much, but wouldn't it be possible to add a similar knob for those expecting the old behavior of breakable boxes?

I fear that is not so easy, because the changes in color setting are at many spots and a toggle would be quite exhaustive. But, even worse, the changes are needed to be compatible with the future LaTeX color implementation Ulrike Fischer is going to do - the old version / toggle would be not functional in future.

**Comment by akiyks** [comment]
Thanks for your explanation.

> ...
> But, even worse, the changes are needed to be compatible with the future LaTeX color implementation Ulrike Fischer is going to do - the old version / toggle would be not functional in future.

I see. 
I'm answering the important one:

> As I commented above: are there deeper problems than new warnings?

No, as far as I can see, there is no visible defects in the resulting PDFs.

Anyway, thanks for the valuable info. Much appreciated.
I'll add a note in our FAQ document saying "these warning messages from tcolorbox and pdfTeX can be safely ignored".

Now closing as "not planned".
Thank you again!

**Comment by T-F-S** [comment]
With https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.2 I made an attempt to get rid of these warnings. Zero height box parts are merged back to the box content and my tests indicate that nothing is lost anymore.

**Comment by akiyks** [comment]
> With https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.2 I made an attempt to get rid of these warnings. Zero height box parts are merged back to the box content and my tests indicate that nothing is lost anymore.

Nice!
I tested v6.0.2 and confirmed that it has got rid of those warnings.

Many thanks.
