### ISSUE TITLE
multicol issue

### ISSUE THREAD

**Issue by ultravioletcatastrophe** [T-F-S/tcolorbox#244]
Hi, I've read the tcolorbox documentation and know that I can't expect a perfect result when using breakable tcolorboxes and multicol, but i'm having a weird issue where paragraph breaks are actually being inserted and deleted, which I don't think is expected behavior. MWE and picture here: https://tex.stackexchange.com/questions/695327/tcolorbox-multicols-tufte-book-inserting-unwanted-paragraph-breaks

**Comment by muzimuzhi** [comment]
- The deletion of paragraph breaks is reported separately in #245, in its general form.
    - The problem reproduces when a `fullwidth` environment starts with a `parbox=false` tcolorbox.
      ```tex
      \documentclass[justified, nofonts, notitlepage, openany, debug]{tufte-book}
      \usepackage{tcolorbox}
      
      \begin{document}
      \begin{fullwidth}
        \begin{tcolorbox}[parbox=false]
          abc \par def \par ghi
        \end{tcolorbox}
      \end{fullwidth}
      \end{document}
      ```
    - Then the case is further simplified to "a list whose content starts with a `parbox=false` tcolorbox" . `fullwidth` is based on `adjustwidth(*)` environment from `changepage` package, and the latter is based on `\list`.
- The insertion of paragraph breaks is actually unwanted tcolorbox breakings. Setting `skin=standard` makes it more clear.
- The misalignment at the top of first column is also related to `breakable` option, which I don't know why as well.

**Comment by T-F-S** [comment]
As @muzimuzhi wrote, the deletion if paragraph breaks is problem/bug further discussed in https://github.com/T-F-S/tcolorbox/issues/245. 

Automatic breakable boxes are not possible inside a `multicol` environment. On page 410ff of the documentation you will find examples how to use manual breaks with `break at`, if you still need to break boxes inside a `multicols` environment, but it is uncomfortable and a kind of final polish for a written document or `multicols` part.

The initial misalignment at the top results from using `breakable` and a sourrounding `fullwidth` environment. Removing one of them will remove the misalignment. Typically, a breakable box should not be inside other constructs, because the box will insert and remove stuff to calculate the remaining height. Inside other constructs, this process may leave visible space behind.
