### ISSUE TITLE
Strange Key Names

### ISSUE THREAD

**Issue by Addlai** [T-F-S/tcolorbox#271]
When I took my first computer programming course, in 1980, we were instructed not to use short or cryptic identifiers, and points were deducted if we did.  I've remained with this bias ever since.

LaTeX and TeX, or course, are notorious for the ineptitude of their programming model, which among other things, places very weird and awkward limitations on identifiers. One of the things I really like about Tikz is that it does not place such weird limitations on identifiers, but freely allows and encourages intelligible identifiers that use full words, spaces, etc.

Because of my biases, I have a hard time keeping identifiers like colupper, colback, colbacktitle, leftupper, top, ... straight, and I prefer not to have to expend time and mental energy looking up such things and deciphering what is wrong when I get unexpected results.

Is there a way to create custom global aliases for tcolorbox's keywords, so I can rename some of the ones I find confusing or hard to remember?

**Comment by muzimuzhi** [comment]
Possible with fancy `pgfkeys` ([unofficial online doc](https://tikz.dev/pgfkeys)) key handlers, though may cause efficiency concerns.

```tex
\documentclass{article}
\usepackage{tcolorbox}

% make aliases under another key prefix
\pgfkeys{
  /mytcbalias/.is family,
  % if "/tcb/<key>" is unknown, try "/mytcbalias/<key>"
  /tcb/.search also={/mytcbalias}
}

\pgfqkeys{/mytcbalias}{
  upper part.color/.style={/tcb/colupper={#1}},
  upper part.font/.style={/tcb/fontupper={#1}}
}

\begin{document}
\begin{tcolorbox}[colupper=cyan, fontupper=\Large\sffamily]
  content
\end{tcolorbox}

\begin{tcolorbox}[upper part.color=cyan, upper part.font=\Large\sffamily]
  content
\end{tcolorbox}
\end{document}
```

![image](https://github.com/T-F-S/tcolorbox/assets/6376638/fac44444-8ccc-48ef-b79d-5dde7c4108d8)

**Comment by Addlai** [comment]
That's an elegant solution. Thanks!

**Comment by Addlai** [comment]
Actually, a problem came up with trying to rename colbacktitle using 
`...
title.color.background/.style={/tcb/colbacktitle={#1}},
...
`
which results in the error message:
ERROR: Package pgfkeys Error: I do not know the key '/mytcbalias/title filled' and I am going to ignore it.

I think it has something to do with the
/tcb/title filled
key, whose documentation states, "... This option is set to true automatically by /tcb/colbacktitle, /tcb/opacitybacktitle, and /tcb/title style, and /tcb/title code. ..." I suspect the alias mechanism isn't compatible with the way tcolorbox sets this variable, but I don't know.

**Comment by muzimuzhi** [comment]
Hmm the tricky current default path problem in `pgfkeys`.

Adding `/mytcbalias/.search also={/tcb}` should work.

Revised example (v2)

```tex
\documentclass{article}
\usepackage{tcolorbox}

% make aliases under another key prefix
\pgfkeys{
  /mytcbalias/.is family,
  % if "/tcb/<key>" is unknown, try "/mytcbalias/<key>"
  /tcb/.search also={/mytcbalias},
  % If "/mytcbalias/<key>" is unknown, try "/tcb/<key>"; if "/tcb/<key>" is
  % again unknown (no recursive ".search also" involved), throw general error
  % about unknown key.
  %
  % Mutual "/.search also" is needed to support aliased "/tcb" style keys, like
  %     /tcb/colbacktitle/.style={{title filled,@colbacktitle={#1}}}
  /mytcbalias/.search also={/tcb}
}

\pgfqkeys{/mytcbalias}{
  upper part.color/.style={/tcb/colupper={#1}},
  upper part.font/.style={/tcb/fontupper={#1}},
  title.color.background/.style={/tcb/colbacktitle={#1}},
}

\begin{document}
\begin{tcolorbox}[colupper=cyan, fontupper=\Large\sffamily]
  content
\end{tcolorbox}

\begin{tcolorbox}[
  title=Title,
  upper part.color=cyan,
  upper part.font=\Large\sffamily,
  title.color.background=gray!80
]
  content
\end{tcolorbox}

% should throw error
\begin{tcolorbox}[key unknown to both prefixes]
  content
\end{tcolorbox}
\end{document}
```

**Comment by muzimuzhi** [comment]
Today I read a [TeX-SX answer](https://tex.stackexchange.com/a/750202) which uses the `/.forward to=<full path to another key>` key handler. It reminds me of this issue and here's an improved approach.

Let's begin from where my first attempt (https://github.com/T-F-S/tcolorbox/issues/271#issuecomment-1985178348) failed:
```tex
\documentclass{article}
\usepackage{tcolorbox}

\pgfkeys{/tcb/.search also={/mytcbalias}}

\pgfqkeys{/mytcbalias}{
  title.color.background/.style={/tcb/colbacktitle={#1}}
}

% ! Package pgfkeys Error: I do not know the key '/mytcbalias/title filled' ...
\tcbset{title.color.background=cyan}

\begin{document}
\end{document}
```

First, `/tcb/title.color.background` is checks. It doesn't exist, then `/mytcbalias/title.color.background` is checked. It exists, so  `/tcb/colbacktitle=cyan` is processed, with default path `/mytcbalias`.

`/tcb/colbacktitle` is a style key which then calls keys `title filled` and `@colbacktitle`. Since they are both relative keys (keys don't start with `/`), so `pgfkeys` uses the current default path (`\pgfkeysdefaultpath`) to construct the full key path. This then requires that, before the key `colbacktitle` is processed, the current default key is set to `/tcb/`. But we had `/mytcbalias`.

```tex
\pgfqkeys{/mytcbalias}{
  title.color.background/.code={\pgfqkeys{/tcb}{colbacktitle={#1}}}
}
```
does the trick. This should be quicker than my second attempt (https://github.com/T-F-S/tcolorbox/issues/271#issuecomment-1986795575), which introduced another `/.search also`.

To simplify the input, you can define a new key handler, for example called `/.alias` with syntax `<key>/.alias={<default path>}{<key-value list>}:
```tex
\documentclass{article}
\usepackage{tcolorbox}

% define new key handler "/.alias"
\pgfkeys{/handlers/.alias/.code 2 args={%
  \pgfkeys{\pgfkeyscurrentpath/.code={\pgfqkeys{#1}{#2={##1}}}}%
}}

% if "/tcb/<key>" is unknown, try "/mytcbalias/<key>"
\pgfkeys{/tcb/.search also={/mytcbalias}}

% define new key as an alias
\pgfqkeys{/mytcbalias}{
  title.color.background/.alias={/tcb}{colbacktitle}
}

% use new key
\tcbset{title.color.background=cyan}

\begin{document}
\end{document}
```

Note that it's not recommended to alter default path without restoration, in nested key-value list. That's why I skipped `title.color.background/.style={/tcb/.cd, colbacktitle={#1}}`.
