### ISSUE TITLE
Is possible to use the `natural height` for the last fragment on sequence in poster?

### ISSUE THREAD

**Issue by nignasi** [T-F-S/tcolorbox#31]
As an example, consider following code. It draws a `tcbposter` with a box which covers part of first column, the second and part of the third column. Third column fragment is too large for the text and it shows empty space. 

If I'm not wrong, this empty space can be shortened if we include another (previous) box on third column and change the last line of `sequence` option. I think its not possible to do it the other way, it is say that last fragment uses its natural height and later one place a box between third fragment and last box on third column.  Is is possible? Is there any way of reducing the empty space, something like: `sequence=... 3 between top and "natural end"`?

Thank you,

Ignasi

[sensetitol-1.pdf](https://github.com/T-F-S/tcolorbox/files/1238763/sensetitol-1.pdf)

```
\documentclass{article}
\usepackage[a4paper,landscape]{geometry}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage[most]{tcolorbox}
\usepackage{lipsum}

\begin{document}
\pagestyle{empty}

\begin{tcbposter}[
coverage ={spread},
poster = {%showframe, 
	columns=3, rows=3,},
boxes = {colframe=black, colback=white, enhanced, attach boxed title to top left={xshift=5mm, yshift*=-\tcboxedtitleheight/2},
boxed title style={colback=black, sharp corners}}
]
\posterbox[adjusted title=Biblioteca Random XYZ]{name=A,column=1,below=top}{\lipsum[1]}
\posterbox[adjusted title=Biblioteca Random XYZ]{name=B,column=1,below=A}{\lipsum[2]}

\posterbox[adjusted title=Biblioteca Random XYZ]{name=D,column=3,above=bottom}{\lipsum[2]}

\posterbox[adjusted title=Biblioteca Random XYZ]{name=C,
	sequence=1 between B and bottom then
	         2 between top and bottom then
	         3 between top and D}{\lipsum[3-8]}
\end{tcbposter}

\end{document}
```

**Comment by T-F-S** [comment]
Sorry for the delay.

Yes, it is possible size the third fragment to have its natural height.
Your code contains a certain complication using the `boxed title` option, but I come to that later.

When a `sequence` is used, the box sequence automatically gets the option `height fixed for=all`. So. all boxes get the predefined height. This can be changed by adding `height fixed for=first and middle` to the box sequence `C` and using `sequence=... 3 between top and bottom`. Both together gives the third fragment with its natural height.

Now, box `D` can be placed `between=C3 and bottom`:

```latex
\documentclass{article}
\usepackage[a4paper,landscape]{geometry}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage[most]{tcolorbox}
\usepackage{lipsum}

\begin{document}
\pagestyle{empty}

\begin{tcbposter}[
  coverage ={spread},
  poster = {%showframe,
            columns=3, rows=3,},
  boxes = {colframe=black, colback=white, enhanced, attach boxed title to top left={xshift=5mm, yshift*=3mm-\tcboxedtitleheight},
           boxed title style={colback=black, sharp corners}}
]
\posterbox[adjusted title=Biblioteca Random XYZ]{name=A,column=1,below=top}{\lipsum[1]}
\posterbox[adjusted title=Biblioteca Random XYZ]{name=B,column=1,below=A}{\lipsum[2]}

\posterbox[adjusted title=Biblioteca Random XYZ,
  height fixed for=first and middle,
  ]{name=C,
 sequence=1 between B and bottom then
          2 between top and bottom then
          3 between top and bottom}{\lipsum[3-8]}%

\posterbox[adjusted title=Biblioteca Random XYZ,add to height=-3mm]{name=D,column=3,between=C3 and bottom}{\lipsum[2]}

\end{tcbposter}

\end{document}
```

Surely, you noted some more differences to your code. The reason is the `boxed title`.
The problem is that the height of the boxed title is added to the (fixed) height of a given box. Therefore, box `D` becomes too large.

My poor man's solution to this problem is that I used `attach boxed title to top left={xshift=5mm, yshift*=3mm-\tcboxedtitleheight}`. Now, we know that all boxes will grow by `3mm` in height and this can be compensated by adding `add to height=-3mm` to achieve the correct height.

**Comment by nignasi** [comment]
Thanks for your answer. Everything is clear now.
