### ISSUE TITLE
label lost in overfull box in breakable tcolorbox

### ISSUE THREAD

**Issue by proteusGIT** [T-F-S/tcolorbox#34]
Hi,

the label lab1 should not be lost due to the overfull box

```
\documentclass{article}

\usepackage{tcolorbox}
\tcbuselibrary{breakable}
\begin{document}

\begin{tcolorbox}[breakable]
\label{lab1}%
\rule{2cm}{19cm}
\end{tcolorbox}
lab1 \pageref{lab1} foo

\end{document}
```

**Comment by T-F-S** [comment]
I can confirm the problem, but currently I do not see a solution by changing the break algorithm. I did a lot of experiments, but my changes for the algorithm produced new and more severe problems for other examples.

Fortunately, this problem can be easily circumvented. As far as I have seen, it can only happen at the very begin of a tcolorbox. Therefore, the label is a label for the tcolorbox itself and should preferably be put inside the options for the tcolorbox (see `lab2` in the code below).

Another way of circumvention is to add an `\mbox{}` before the label, see `lab3` below.

```latex
\documentclass{article}

\usepackage{tcolorbox}
\tcbuselibrary{breakable}

\begin{document}

\begin{tcolorbox}[breakable]
\label{lab1}
\rule{2cm}{19cm}
\end{tcolorbox}
Problem: lab1 \pageref{lab1} foo

\clearpage

\begin{tcolorbox}[breakable,label=lab2]
\rule{2cm}{19cm}
\end{tcolorbox}
No problem: lab2 \pageref{lab2} foo

\clearpage

\begin{tcolorbox}[breakable]
\mbox{}\label{lab3}
\rule{2cm}{19cm}
\end{tcolorbox}
No problem: lab3 \pageref{lab3} foo

\end{document}
```

So, currently, I hesitate to change the break algorithm, because changes typically produce a lot of new problems for existing documents and I was not able to find a bullet-proof solution. Also, I hope that the easy ways of circumvention moderate the weight of the problem.

**Comment by proteusGIT** [comment]
This solves the problem of course.
Also, I think, people will not overlook missing references.
However, maybe tcolorbox could _detect_ the problem an typeout some hint.

**Comment by T-F-S** [comment]
For the next version, I added a new warning `Discard zero height first box part due to break problems (possible loss of zero height content)` for the situation.

**Comment by T-F-S** [comment]
A warning `Discard zero height first box part due to break problems (possible loss of zero height content)` is implemented for `tcolorbox 4.13 (2018/03/22)`.

**Comment by T-F-S** [comment]
In the same situation, an `\index` can get lost as just happened with an document of mine. 

The new warning also helped here :-)

**Comment by TinchoteSK** [comment]
Thanks a lot for the analysis and the workaround. I had lot of boxes giving me that problem!

**Comment by muzimuzhi** [comment]
> Another way of circumvention is to add an `\mbox{}` before the label, see `lab3` below.

Or `\leavevmode`. (Sorry for my bothering.)

**Comment by TinchoteSK** [comment]
Thanks :) The mbox hack worked for me, so I'm not touching it again :D
