### ISSUE TITLE
Problem with `listing side text`

### ISSUE THREAD

**Issue by nignasi** [T-F-S/tcolorbox#38]
As it's shown in [tcolorbox: unset or overrule option “listing side text”](https://tex.stackexchange.com/q/420468/1952), when option `listing side text` is used it's is not completely overwritten by `listing above text`. Upper (listing) box keeps divided in two divisions and mid rule is drawn.

    \documentclass{article}
    \usepackage[most]{tcolorbox}

    \begin{document} 
    \begin{tcblisting}{title=Text above}
    \LaTeX{} in a Box
    \end{tcblisting}

    \begin{tcblisting}{title=Text below, listing above text}
    \LaTeX{} in a Box with a long long long long line
    \end{tcblisting}

    \tcbset{listing side text}

    \begin{tcblisting}{title=Text aside}
    \LaTeX{} in a Box
    \end{tcblisting}

    \begin{tcblisting}{title=Text below?, listing above text}
    \LaTeX{} in a Box with a long long long long line
    \end{tcblisting}

    \end{document}

**Comment by T-F-S** [comment]
The observation is correct, because `listing side text` is a convenience style to set `listing and text` and `sidebyside`. Therefore, `listing above text` reverts the effects of `listing and text`, but `sidebyside` still is active.

For the given example, the solution is to add `sidebyside=false` to turn back to the default behavior:

```latex
\documentclass{article}
\usepackage[most]{tcolorbox}

\begin{document}
\begin{tcblisting}{title=Text above}
\LaTeX{} in a Box
\end{tcblisting}

\begin{tcblisting}{title=Text below, listing above text}
\LaTeX{} in a Box with a long long long long line
\end{tcblisting}

\tcbset{listing side text}

\begin{tcblisting}{title=Text aside}
\LaTeX{} in a Box
\end{tcblisting}

\begin{tcolorbox}
Test
\tcblower
Lower at right side
\end{tcolorbox}

\begin{tcblisting}{title=Text below?, listing above text, sidebyside=false}
\LaTeX{} in a Box with a long long long long line
\end{tcblisting}

\end{document}
```

Currently, the documentation contains no hint about that. If the options are not globally used, there is no problem. There are four option settings which act in the same way:

```latex
text side listing/.style={sidebyside,text and listing},%
listing side text/.style={sidebyside,listing and text},%
comment side listing/.style={sidebyside,comment and listing},%
listing side comment/.style={sidebyside,listing and comment},%
```
I am going to add some notes to the documentation for theses options to help users to understand their application (and how to revert them).

**Comment by nignasi** [comment]
Thank you for your detailed explanation.
