### ISSUE TITLE
Incorrect box height in poster when using `between` and boxed title

### ISSUE THREAD

**Issue by Faturan** [T-F-S/tcolorbox#44]
In a `tcbposter`, using `between` to place a box with a boxed title causes the box to be higher than expected. It seems that `between` doesn't consider the height of the title's box.

Here is a MWE: 
```latex
\documentclass{article}
\usepackage[poster]{tcolorbox}

\begin{document}
\begin{tcbposter}[poster={showframe},boxes={attach boxed title to top center}]
\posterbox[title=test]{between=top and bottom}{}
\end{tcbposter}
\end{document}
```

**Comment by T-F-S** [comment]
I fear, there is no really satisfying solution, because a box with a detached title does not know the title height during construction. Therefore, the fixed height is used for the box only. Later, the flowing title is added.

But, if you know the height of your title(s), there is a way to circumvent the problem:

```latex
\documentclass{article}
\usepackage[poster]{tcolorbox}

\begin{document}
\begin{tcbposter}[poster={showframe},boxes={attach boxed title to top center,
    boxed title style={height=7mm,valign=center},
  }]
\posterbox[title=test,add to height=-7mm]{between=top and bottom}{}
\posterbox[title=Another test,add to height=-7mm]{column=2,between=top and row4}{}
\end{tcbposter}
\end{document}
```

![test302_output](https://user-images.githubusercontent.com/7982989/40915994-5c3719a8-67fe-11e8-9f63-74526ef9df14.png)

The fixed title height is not so very nice, but hopefully you can use this example for your application.
