### ISSUE TITLE
cann't load tcbskinsjigsaw.code.tex in tcolorbox version:4.13

### ISSUE THREAD

**Issue by CentUser** [T-F-S/tcolorbox#45]
My system:
TeX 3.1415926 (TeX Live 2013), centos 7 , yum version of texlive.
I put those files downloaded here to /usr/share/texlive/texmf-dist/tex/latex/tcolorbox as is said in README.
And I run xelatex, encountered the following error:
(/usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcbbreakable.code.tex
Library (tcolorbox): 'tcbbreakable.code.tex' version '4.13'
)) (/usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcbskins.code.tex
Library (tcolorbox): 'tcbskins.code.tex' version '4.13'
! I can't find file `tcbskinsjigsaw.code.tex'.
<to be read again> 
                   \relax 
l.1894 \tcbuselibrary{skins@jigsaw}
                                   
(Press Enter to retry, or Control-D to exit)
Please type another input file name: 

while I straced the programme, and find out that, when xelatax is reading tcbskins.code.tex, it first looks for it in current directory, and if it could not find it, it would try /usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcbskins.code.tex which could be found clearly. 
Yet, when it comes to tcbskinsjigsaw.code.tex, xelatex only looks for the file in current working directory, and not try the /usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcbskinsjigsaw.code.tex. 

example:
\documentclass{article}
\usepackage{tcolorbox}
\tcbuselibrary{raster,listings}

\begin{document}
\begin{tcbitemize}
\tcbitem test
\end{tcbitemize}

\end{document}

**Comment by T-F-S** [comment]
Your question is of a more general nature: 'How do I install a package on TeXLive'.
Since I do not use TeXLive, I cannot really give good advice. 

The best thing would be to update TeXLive to a more recent version than 2013, because you may run into trouble using an up-to-date `tcolorbox` with very old versions of `tikz`, `etoolbox`, etc.

If you cannot update TeXLive, then following the instructions from
https://en.wikibooks.org/wiki/LaTeX/Installing_Extra_Packages
may help.
