### ISSUE TITLE
toggle left and right seems to be broken

### ISSUE THREAD

**Issue by gloignon** [T-F-S/tcolorbox#5]
When using breakable, toggle left and right and oversize at the same time, the boxes will not display properly. The text within the box looks ok, but the box itself does not sit at the right place.

I spotted this problem when I updated to 4.71, then changed to 4.72 and the problem was still there. (didn't test for any other versions).

Example code for the box:

\begin{tcolorbox}[left=\marginparwidth,oversize,enhanced,check odd page, breakable, toggle left and right]

This code worked in 3.4 but is broken now.

I should also mention that you are doing awesome work for the LaTeX community! :)

**Comment by T-F-S** [comment]
In version 3.60, there was a bug fix for `enlarge .. by` which did not work for settings with em or ex units. These values were processed too late and are processed earlier now which causes the change of behaviour for your code.

Actually, the behaviour now is correct and the old one was not. The reason is that `tcolorbox` has two independent toggling options:

- `toggle left and right` toggles normal geometry settings.
- `toggle enlargement` toggles bounding box changes. With `oversize`, there is a bounding box change.

To conclude the explanation: The `oversize` and `toggle left and right` combination did also a bounding box change in the past using a side effect, but now works correctly in not doing so.

And the solution for the problem is: add `toggle enlargement` to your option list to get the behaviour you need :-)

I will see if I can put some hints for that into the documention, because that can easily be overseen.

**Comment by gloignon** [comment]
Thank you Thomas.

I tested your solution right away and it compiled flawlessly in Texlive 2015 with tcolorbox 3.72.

Keep up the good work!
