### ISSUE TITLE
cambridge7a.cls footnotes in breakable tcolorbox

### ISSUE THREAD

**Issue by rlhatton** [T-F-S/tcolorbox#51]
When using the cambridge7a class, if the breakable=true flag is set on a box, the footnote marks on footnotes inside the box are not raised from the text.

The problem appears to be that cambridge7a.cls handles footnotes in minipages differently from footnotes in the main text. I can fix the problem by inserting \let\@makefnmark\@makempfnmark at line 81 of tcbbreakable.code.tex (matching line 1712 from cambridge7a.cls), and expanding the line to

\ifx\@makempfnmark\@undefined\else\let\@makefnmark\@makempfnmark\fi

appears to make the code back-compatible with classes that don't define a separate minipage footnote marker.

**Comment by T-F-S** [comment]
Where could I find a recent version of `cambridge7a.cls`? 

It is not on CTAN and I did not found it at Cambridge University Press... Is it still maintained by Cambridge University Press?

**Comment by rlhatton** [comment]
I've sent email to the Cambridge technical support staff asking for an updated link. Since I downloaded my files, they have changed their author resources page (and I think I missed being brought into their new account-based system because of a change in institutions). I'll report back.

**Comment by rlhatton** [comment]
The files are at

https://www.cambridge.org/authorhub/application/files/4815/1964/5335/cambridge7A_authored.zip <https://www.cambridge.org/authorhub/application/files/4815/1964/5335/cambridge7A_authored.zip>

**Comment by T-F-S** [comment]
I looked into the code and I think that the changes of `cambridge7a.cls` are too specific to justify a global code change for `tcolorbox`.  

If `\@makempfnmark` would e.g. be defined by another class or package for some specific purpose, then it may be bad to use it as footnote mark for `tcolorbox`.

Nevertheless, I see at least two approaches for documents based on `cambridge7a.cls` to solve the problem.

- Add the following code to the preamble
```latex
\makeatletter
\tcbset{cambreakable/.style={%
  breakable,
  code={\ifx\@makempfnmark\@undefined\else\let\@makefnmark\@makempfnmark\fi}}%
}
\makeatother
```
and use `cambreakable` instead of `breakable` for breakable boxes (but not as global option for whole document).

- If you set every box to be `breakable` globally (not advised!), then use the following instead:
```latex
\makeatletter
\tcbset{every box/.style={%
  code={\ifx\@makempfnmark\@undefined\else\let\@makefnmark\@makempfnmark\fi}}%
}
\makeatother
```

**Comment by rlhatton** [comment]
Thanks!

(Should I close out this issue?)

**Comment by T-F-S** [comment]
Yes, I think so (I close it).
