### ISSUE TITLE
Some questions about toprule/bottom rule at break and others

### ISSUE THREAD

**Issue by nignasi** [T-F-S/tcolorbox#55]
According to documentation toprule at break sets the line width of the top rule if the box is breakable and a similar explanation is given for bottomrule at break.

Top and bottom rules at break are not drawn, therefore why to set their size?

If these sizes are fixed to adjust box size when these rules are drawn by the author, why should we fix the size? Option `toprule at break` (without `=...`) fails.

I think that these options should automatically draw top and bottom rules or change documentation and explicitely say that an overlay command should be invoked to draw the lines.

Another question (suggestion). Could be possible to save tcolorbox colors in some public colornames that could be used with overlay commands or other commands? This way, changing colback all related command could automatically change without need to define new colors.

I know I could do it by declaring my own colors and use them in tcolorbox definition, but whynot use default colors? 

Thank you very much,

Ignasi

**Comment by T-F-S** [comment]
About `toprule at break` and `bottomrule at break`: 
`tcolorbox` skins do not change the geometry of the boxes. Therefore, all boxes have a specified rule width on all four sides even if the selected skin does not draw a rule visually. In Section 17.8 from Page 379 the break sequence for different skins is displayed - some of them draw rules and some not.
Therefore, this option is needed.

For colors:
Since version I-do-not-know-when, color settings are saved into colornames and they can be used for own macros. But, I seem to have forgotten to document the names to make them *officially* available. The color names are
- `tcbcol@back`
- `tcbcol@frame`
- `tcbcol@upper`
- `tcbcol@lower`
- `tcbcol@title`
- `tcbcol@backtitle` (if used)
- `tcbcol@backlower` (with skins library)

I will document these color names for the next version.

**Comment by T-F-S** [comment]
For 'official' usage, I renamed the color names now (`@` removed).

These color names are documented in version 4.20.

**Comment by nignasi** [comment]
Thank you.
