### ISSUE TITLE
\refCom, \refEnv and \refKey fail with beamer class if not used with their starred variants

### ISSUE THREAD

**Issue by dbitouze** [T-F-S/tcolorbox#63]
The `documentation` library provides the nice command `\refCom{〈name〉}` that references a documented LaTeX macro by writing something like `\〈name〉\textsuperscript{P. \pageref{〈label of the macro〉}}` and make this an hyperlink to where `\〈name〉` is documented.

If used with its starred variant `\refCom*{〈name〉}`, there is no page reference and no hyperlink, just `\〈name〉`.

The commands `\refEnv` and `\refKey` that reference LaTeX environments and keys work the same way.

So far, so good. Except that, as pointed out by the following MCE, with `beamer` class, the commands have to be used with their starred variants, otherwise the compilation fails with the following error message:

>! Undefined control sequence.
\reserved@a *->\@pagerefstar

It could be nice to both:

- fix this issue,
- provide an option that globally removes the page references and hyperlinks for these commands: one could  want this globally.

```latex
\documentclass{beamer}
%
\usepackage{tcolorbox}
\tcbuselibrary{documentation}
%
\begin{document}
%
\begin{frame}
  \begin{docCommand}{foomakedocSubKey}{\marg{name}\marg{key path}}
    Creates a new environment \meta{name} based on \refEnv{docKey} for the
    documentation of keys with the given \meta{key path}.
  \end{docCommand}
  %
  We have created \refCom{foomakedocSubKey} as an example.
\end{frame}
%
\end{document}
```

**Comment by T-F-S** [comment]
Currently, I have not much time to investigate further, but this seems to be a `beamer` / `hyperref` problem.

`hyperref` provides a macro `\pageref*` (used by `tcolorbox`) which seems to get broken by some `beamer` modifications(?). The same error is produced by the following code:

```latex
\documentclass{beamer}

\usepackage{hyperref}

\begin{document}

\begin{frame}
  Test\label{mytest}
\end{frame}

\begin{frame}
  Reference to Test: \pageref*{mytest}
\end{frame}

\end{document}
```

**Comment by muzimuzhi** [comment]
Short answer:
1. `beamer` does not load `hyperref` fully, which means usage `\pageref*` is not supported in `beamer`.
1. It is recommended to use `\ref{key}` with `\begin{frame}[label=key]`, since the output of `\pageref` would be wrong if overlay is used. See https://tex.stackexchange.com/a/478422

Detailed (if any) explanation:
1. `beamer` loads `hyperref` with `implicit=false` as one of its options
1. This option will end the loading of `hyperref` package at an early stage, where
   1. `\pageref` is redefined, and the star form `\pageref*` leads to `\@pagerefstar` command, but
   1. `\@pagerefstar` is never defined

See https://github.com/ho-tex/hyperref/issues/100, an issue opened by myself and inspired by the current issue, for more info.
