### ISSUE TITLE
Internal colors names renamed: their old names should still be provided

### ISSUE THREAD

**Issue by dbitouze** [T-F-S/tcolorbox#68]
With version 4.20 of `tcolorbox`, internal colors names: `tcbcolframe`, `tcbcolback`, `tcbcolbacktitle`, `tcbcolbacklower`, `tcbcolupper`, `tcbcollower`, `tcbcoltitle` have been renamed. 

IMHO, their old legacy names (containing an `@`) should still be provided, since some users (for instance me :) used them, getting inspiration from some examples of the `tcolorbox`' documentation, e.g. currently the one page 165 that contains `\path[fill=tcbcolback!30!black]`.

**Comment by T-F-S** [comment]
Typically, I hesitate very much to change a documented feature. But, the color names never were documented (even if used in one example).

Since [Request 55](https://github.com/T-F-S/tcolorbox/issues/55), I thought about making the names official.

To keep the old names and just document them would have been one option. Finally, I droped this idea because the naming should clearly indicate the *official* nature. If an `@` is part of the name, a macro or name or feature is internal and due to be changed in future. It may be used by users, but they have to be prepared to adapt code in future.

Still, I also hesitate to change internal macros and names, because every change to do something good may imply some unwanted side effects. In this case, I decided to change the names even if I am forced to change some applications of myself - or you or others. Keeping the old names as deprecated for some time would just shift the time of adaption.

For all internal color names, just the `@` was removed. So, the adaption of affected user code can be done by a simple text replacement:

**Replace `tcbcol@` by `tcbcol`**

This should do the trick. I've done it with several of my own applications.

I hope I did not cause too much trouble with this change. This good side is that color names are now official and (hopefully) never change in future.

**Comment by dbitouze** [comment]
>If an @ is part of the name, a macro or name or feature is internal and due to be changed in future. It may be used by users, but they have to be prepared to adapt code in future.

I agree but, because these names came up from the deep, usually a secret place of gods, through the `tcolorbox`'s documentation, poor common mortals as us dared to use them, unconscious of the potential dangers :)

**Comment by nigeder** [comment]
oh,poor me!
