### ISSUE TITLE
newtcbtheorem access to title

### ISSUE THREAD

**Issue by proteusGIT** [T-F-S/tcolorbox#69]
In the manual on page 126 (8.3) I want to use the title of the exercise in the title of the solution.
I tried \tcbtitle and \tcbtitletext but they are empty.
However, I used this is the context of newtcbtheorem for theorems/proofs.
The following modification with \tcbtitletext workds on the original example from page 126.

        \documentclass{article}

        \usepackage{amsmath}
        \usepackage[most]{tcolorbox}

        \begin{document}

        \makeatletter

        \newtcbtheorem
            {mytheorem}
            {Theorem}
            {
            coltitle=black,
            breakable,
            label={theorem:\thetcbcounter},
            after upper={\par\hfill{\itshape Proof on page~\pageref{proof:theorem:\thetcbcounter}}},
            lowerbox=ignored,
            savelowerto=proofs/proof-\thetcbcounter.tmp,
            record={\string\solution{\tcbtitletext}{theorem:\thetcbcounter}{proofs/proof-\thetcbcounter.tmp}}
            }{theorem}
            
        \NewTotalTColorBox{\solution}{mmm}{%
        enhanced,colframe=red!20!black,colback=yellow!10!white,coltitle=red!40!black,
        fonttitle=\bfseries,
        underlay={\begin{tcbclipinterior}
        \shade[inner color=red!50!yellow,outer color=yellow!10!white]
        (interior.north west) circle (2cm);
        \draw[help lines,step=5mm,yellow!80!black,shift={(interior.north west)}]
        (interior.south west) grid (interior.north east);
        \end{tcbclipinterior}},
        title={Solution (#1) of Exercise~\ref{exercise@#2} on page~\pageref{exercise@#2}:},
        phantomlabel={solution@#2},
        attach title to upper=\par,
        }{\input{#3}}
        \tcbset{no solution/.style={no recording,after upper=}}

        \makeatother

        \tcbstartrecording
        \begin{mytheorem}[title={FOO}]
        Compute the derivative of the following function:
        \begin{equation*}
        f(x)=\sin((\sin x)^2)
        \end{equation*}
        \tcblower
        The derivative is:
        \begin{align*}
        f'(x) &= \left( \sin((\sin x)^2) \right)'
        =\cos((\sin x)^2) 2\sin x \cos x.
        \end{align*}
        \end{mytheorem}

        \tcbstoprecording

        \tcbinputrecords

        \end{document}

**Comment by joulev** [comment]
Although I am not the author of the package, I have some thoughts:
1. This seems like a question rather than an issue report. Therefore, I think you should ask it in some online forum e.g. [TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/), where there are many TeXperts who can answer it quickly. Note that [Thomas Sturm](https://tex.stackexchange.com/users/30617/thomas-f-sturm) &ndash; the author of `tcolorbox` &ndash; is also active there, and he may answer your question.
2. Is your TeX distribution updated? With the most recent MiKTeX, my page 126 is different than yours. In my manual (`tcolorbox` version 4.20), page 126 is section 6.2, not 8.3. Section 8.3 is on page 131.

**Comment by proteusGIT** [comment]
The problem also appears in the latest version; I just had an old documentation.
I have simplified the example to demonstrate the issue better.
In the following example, the `\tcbtitletext` is lost when the line marked by `%%%%% <----` is commented.
This is unexpected to me.

    \documentclass{article}

    \usepackage{tcolorbox}

    \begin{document}
    
    \begin{tcolorbox}[
        title={FOO},
        coltitle=red,
        attach title to upper=,%%%%%% <---
        ]
        text (\tcbtitletext)
    \end{tcolorbox}

    \end{document}

This then also leeds presumably to the fact that the \`tcbtitletext` is not recorded.

    \documentclass{article}

    \usepackage{tcolorbox}
    \tcbuselibrary{skins,xparse}

    \begin{document}

    \tcbstartrecording
    
    \begin{tcolorbox}[
        title={FOO},
        colframe=black,colback=black!10!white,coltitle=red,
        attach title to upper=,%%%%%% <---
        record={\string\solution{\protect\tcbtitletext}},
        ]
        text
    \end{tcolorbox}

    \newcommand{\solution}[1]{(#1)}
    

    \tcbstoprecording

    \tcbinputrecords

    \end{document}

**Comment by T-F-S** [comment]
`\tcbtitletext` is available only, if the option `detach title` is used. The style `attach title to upper` uses this option and, therefore, `\tcbtitletext` can be applied.

Without `detach title`, the title content is not available to the user, but applied internally to its default position.

For your application case, I recommend another approach with an own style like `mytitle`.

The first variant of `mytitle` sets the title and saves the record:
```latex
   mytitle/.style={
     title={#1},
     record={\string\solution{#1}},
   }
``` 
The full example is:
```latex
\documentclass{article}

\usepackage{tcolorbox}
\tcbuselibrary{skins,xparse}

\tcbset{
  mytitle/.style={
    title={#1},
    record={\string\solution{#1}},
  }
}

\begin{document}

\tcbstartrecording

\begin{tcolorbox}[
    mytitle={FOO},
    colframe=black,colback=black!10!white,coltitle=red,
    ]
    text
\end{tcolorbox}

\newcommand{\solution}[1]{(#1)}


\tcbstoprecording

\tcbinputrecords

\end{document}
```


A second variant saves the title into a macro `\mytitletext` for later use:
```latex
  mytitle/.style={
    title={#1},
    code={\def\mytitletext{#1}},
  }
```
The full example is:
```latex
\documentclass{article}

\usepackage{tcolorbox}
\tcbuselibrary{skins,xparse}

\tcbset{
  mytitle/.style={
    title={#1},
    code={\def\mytitletext{#1}},
  }
}

\begin{document}

\tcbstartrecording

\begin{tcolorbox}[
    mytitle={FOO},
    colframe=black,colback=black!10!white,coltitle=red,
    record={\string\solution{\protect\mytitletext}},
    ]
    text
\end{tcolorbox}

\newcommand{\solution}[1]{(#1)}


\tcbstoprecording

\tcbinputrecords

\end{document}
```

Since you need the title for the solution, I further recommend to make the title a mandatory parameter for your environments (but this depends on your use case).
