### ISSUE TITLE
Weird behaviour of \\ when using ragged2e and tcolorbox

### ISSUE THREAD

**Issue by jnoordsij** [T-F-S/tcolorbox#72]
### Description
 
When using both the ragged2e and tcolorbox packages, the first time \\ is used in a tcolorbox (when parbox is set to false), it does not trigger a line ending but a paragraph break instead, due to what seems to be some missing negative glue.

### MWE
```
\documentclass{article}

\usepackage{parskip}
\usepackage{tcolorbox}
\setlength{\parskip}{\baselineskip}
\usepackage[document]{ragged2e}

\begin{document}

\begin{tcolorbox}[parbox=false]
	Line 1\\
	Line 2\\
	Line 3
\end{tcolorbox}

\end{document}
```

**Comment by T-F-S** [comment]
I do not know or use the `ragged2e` package, but from its documentation it seems to be clear that it tempers with a lot of paragraph glue and skip values. Also, the `parbox=false` tries to reset `parbox` settings to normal text settings. Obviously, this gives a problem.

I do not see a reasonable way to avoid this by altering the package code. Sometimes, some packages just do not work well together, if both packages temper with the same TeX settings.

But, for your example, inserting an additional `\par` to the box content seems to work:

```latex
\documentclass{article}

\usepackage{parskip}
\usepackage{tcolorbox}
\setlength{\parskip}{\baselineskip}
\usepackage[document]{ragged2e}

\begin{document}

\begin{tcolorbox}[parbox=false,before upper=\par]
	Line 1\\
	Line 2\\
	Line 3
\end{tcolorbox}

\end{document}
```

I cannot guarantee that this really solves the problem, because I found it just by experimental guessing.
