### ISSUE TITLE
savelowerto - input - File ended while scanning use of \next. 

### ISSUE THREAD

**Issue by noordo** [T-F-S/tcolorbox#77]
An example that triggers the error : "File ended while scanning use of \next."

`\begin{tcolorbox}[savelowerto=test.tex]`
`\input{exercice.tex}`
`\end{tcolorbox} `

The contents of the exercice.tex file :

`Sujet de l'exercice`
`\tcblower`
`Correction de l'exercice`

There is no error if I put the code directly :

`\begin{tcolorbox}[savelowerto=test.tex]`
`Sujet de l'exercice`
`\tcblower`
`Correction de l'exercice`
`\end{tcolorbox} `

Thanks

**Comment by T-F-S** [comment]
This is a problem that cannot be solved because of `TeX`nical limitations.

`\tcblower` is a special macro which ends a *savebox* for the upper part and starts a new one for the lower part. Using it inside the input file does no trigger this operation. I see no way for an implementation which would work as intended by your code.
