### ISSUE TITLE
Conflict between `coverage` width and `poster` width

### ISSUE THREAD

**Issue by nignasi** [T-F-S/tcolorbox#98]
It seems that `coverage` and `poster` in `tcbposter` use two different values to fix poster width. When a certain width is fixed in `poster` options, this value is not inherited by `coverage` and the result is wrong. But when `width` is fixed in `coverage` the poster looks correct.

There is no problem when the `tcbposter` is intended for a "real" poster, but if you want to use `tcbposter` to create a figure to be inserted into another document, it's necessary to understand this behaviour. May be a comment into documentation about this conflict could be enough.

\documentclass{article}
\usepackage[most]{tcolorbox}
\begin{document}
\begin{tcbposter}[
	poster={height=5cm, width=5cm, showframe},
	coverage={colback=cyan!30}
	]
\end{tcbposter}

\begin{tcbposter}[
	poster={height=5cm, showframe},
	coverage={colback=cyan!30, width=10cm}
	]
\end{tcbposter}

\begin{tcbposter}[
	poster={height=5cm, width=13cm, showframe},
	coverage={colback=cyan!30}
	]
\end{tcbposter}

\end{document}

This is the result

![dibuix](https://user-images.githubusercontent.com/2562430/79735297-5521cc00-82f8-11ea-8429-01330462eaca.png)

**Comment by T-F-S** [comment]
I agree that the documentation should contain more hints on how `coverage` and `poster` work together.

- Without a `coverage`, the `poster` is sized according to paper dimensions *or* according to the `width` and `height` given as `poster` options.

- With a `coverage`, the `poster` width is sized according to the `coverage` width (`\linewidth` by default) *or* according to the `width` given as `poster` option (`coverage` stays unchanged).

- With a `coverage`, the `poster` height is sized according to the `coverage` height, if a fixed height is given there, *or* according to the `height` given as `poster` option. The `coverage` stays unchanged, if it is fixed, or adapts to the poster, if it is not a fixed height.

I think the best advice is to set `width` and `height` as `coverage` options, if there is a `coverage`. Otherwise, set `width` and `height` as `poster` options.

```latex
\documentclass{article}
\usepackage[most]{tcolorbox}
\begin{document}
\begin{tcbposter}[
  coverage={colback=cyan!30, height=5cm, width=6cm},
  poster={showframe},
]
\end{tcbposter}

\begin{tcbposter}[
  coverage={colback=cyan!30, height=7cm, width=8cm},
  poster={showframe},
]
\end{tcbposter}

\begin{tcbposter}[
  coverage={colback=cyan!30, height=4cm, width=10cm},
  poster={showframe},
]
\end{tcbposter}

\end{document}
```

![test_337_output](https://user-images.githubusercontent.com/7982989/79755387-53b4cb80-8319-11ea-9fdc-1b47f60d736e.jpg)

**Comment by T-F-S** [comment]
Documentation expanded for version 4.30 (2020-04-28).
